
spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  jwt:
    secret: ${TOKEN_SECRET}
    toeknValidTime: ${TOKEN_VALID_TIME}

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true

aes:
    secret-key: ${AES_SECRET_KEY}
    init-vector: ${AES_INIT_VECTOR}

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_ACCESS_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 9000