
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/careerfestival
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver


  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
        default_batch_fetch_size: 1000

  jwt:
    secret: ${TOKEN_SECRET}


#  security:
#    oauth2:
#      client:
#        registration: # OAuth 로그인 시 설정한 Application의 정보를 사용하여 AccessToken을 Authorization Server에게 발급받을 때 사용
#          naver:
#            client-id: LnoTwWvUxWxK4iTGMV1r
#            client-secret: eKZgzGuffn
#            redirect-uri: http://localhost:9000/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope: name, email, profile_image
#            client-name: Naver
#
#        provider: # AccessToken을 Authorization Server에게 발급 받은 후, 해당 AccessToken으로 Resource Server의 API를 사용할 때 provider 부분의 정보를 사용하여 API 호출
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response


server:
  port: 9000