
spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create-drop
        default_batch_fetch_size: 1000

  jwt:
    secret: ${TOKEN_SECRET}
    toeknValidTime: ${TOKEN_VALID_TIME}

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_ACCESS_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${gimjeonggeon386@gmail.com}
    password: ${xvhf hqid kbmu aeyx}
    auth: true
    starttls:
      enable: true
      required: true
  subject:
    member:
      registration: Thank you for joining our cafe!
server:
  port: 9000