
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/careerfestival
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}

  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
server:
  port: 9000

  jwt:
    secretKey: ${SECRET_KEY}
    toeknValidTime: ${TOKEN_VALID_TIME}